version: '3'
services:
  saltmaster-local:
    image: erwindon/saltgui-saltmaster
    hostname: saltmaster-local
    ports:
      - 4505:4505
      - 4506:4506
      - 3333:3333
    volumes:
    - ./srv/:/srv/
    - ./conf/master:/etc/salt/master
    - ../saltgui:/saltgui
    entrypoint: /usr/bin/supervisord

  saltminion-ubuntu:
    image: erwindon/saltgui-saltminion-ubuntu
    hostname: saltminion-ubuntu
    depends_on:
       - saltmaster-local
    restart: on-failure
    entrypoint: /usr/bin/salt-minion

  saltminion-debian:
    image: erwindon/saltgui-saltminion-debian
    hostname: saltminion-debian
    depends_on:
       - saltmaster-local
    restart: on-failure
    entrypoint: /usr/bin/salt-minion

  saltminion-centos:
    image: erwindon/saltgui-saltminion-centos
    hostname: saltminion-centos
    depends_on:
       - saltmaster-local
    restart: on-failure
    entrypoint: /usr/bin/salt-minion
